### PR TITLE
Improved modern fortran compliance

### PR DESCRIPTION
**Pull request by scemama**
This fixes issue #146, please merge this after #145.

Note: The `import` statement imports the `iso_c_binding` elements from the module, so `use iso_c_binding` is not necessary inside the functions.

### CODE REVIEW

**Review by q-posev — APPROVED** [review]
Looks good to me, thanks! 
@scemama have you checked that there are no warning printed now with `-Wuse-without-only ` and `gfortran`?

**Comment by q-posev** [comment]
@scemama @stefabat looks like the merge of PR #145 breaks the compilation of `master` and this branch. 
The error is `Error: Parameter ‘c_int32_t’ at (1) has not been declared or is a variable, which does not reduce to a constant expression`. 

Why was the change of return type of `trexio_info` important in the first place? We never had issues with it and the Fortran module was tested on 20 archs from Debian build farm and it worked just fine...

**Comment by q-posev** [comment]
Nevermind, my bad...

**Review by q-posev — APPROVED** [review]
One-line import

**Comment by scemama** [comment]
@q-posev Is it all good now?

**Comment by q-posev** [comment]
@scemama no, looks like something broke when I merge `master` with PR #145 into this branch (there was a git conflict which I had to solve). Now the compilations fails at `trexio_open_c`

**Comment by q-posev** [comment]
Found it!

**Pull request merged**
