### PR TITLE
Jastrow

### PR DESCRIPTION
**Pull request by scemama**

### CODE REVIEW

**Comment by scemama** [comment]
I added the Jastrow group in the Correlation factors section.

There are many diffs because I reorganized the trex.org file as follows:

◉ Metadata (metadata group)...                    
◉ System                                          
 ○ Nucleus (nucleus group)...                     
 ○ Cell (cell group)...                           
 ○ Periodic boundary calculations (pbc group)...  
 ○ Numerical integration grid (grid group)...      
 ○ Electron (electron group)...                   
 ○ Ground or excited states (state group)...      
◉ One-electron basis                              
 ○ Basis set (basis group)...                     
 ○ Effective core potentials (ecp group)...       
 ○ Atomic orbitals (ao group)...                  
 ○ Molecular orbitals (mo group)...               
◉ N-electron basis                                
 ○ Slater determinants (determinant group)...     
 ○ Configuration state functions (csf group)...   
 ○ Amplitudes (amplitude group)...                
 ○ Reduced density matrices (rdm group)...        
◉ Correlation factors                             
 ○ Jastrow factor (jastrow group)...              
◉ Quantum Monte Carlo data (qmc group)...

**Review by q-posev — CHANGES_REQUESTED** [review]
Thanks @scemama ! 

Have this been tested? I noticed that the new `jastrow` group has for example: ` ~een_num~     | ~dim~    | ~(nucleus.num)~`. Normally this should not work since we do not support arrays of `dim` type. Especially since you later use this `dim` in the `| ~een~         | ~float~  | ~(jastrow.een_num)~ `, which value of `jastrow.een_num` will be used? We had the same issue with the `non_local` components in the `ecp` group and ended up re-structing the whole group to accommodate all options. 

I also find the `One-/N-electron basis` reorganization slightly confusing.

**Comment by scemama** [comment]
You are right! I have changed `een` and `een_num` to make them depend on the number of nuclei, but it does not make sense now... I will fix that. Thanks!

**Comment by scemama** [comment]
OK, I fixed the dim problem and added some tests. Everything seems OK now.

I restructured like that:
◉ System                                                                                                                                                                 
*○ Nucleus (nucleus group)...                                                                                                                                            
*○ Cell (cell group)...                                                                                                                                                  
*○ Periodic boundary calculations (pbc group)...                                                                                                                         
*○ Electron (electron group)...                                                                                                                                          
*○ Ground or excited states (state group)...                                                                                                                             
◉ Basis functions                                                                                                                                                        
*○ Basis set (basis group)...                                                                                                       
*○ Effective core potentials (ecp group)...                                                                                                                              
*○ Numerical integration grid (grid group)...                                                                                                                            
◉ Orbitals                                                                                                                                                               
*○ Atomic orbitals (ao group)...                                                                                              
*○ Molecular orbitals (mo group)...                                                                
◉ Multi-determinant information                                                                                                                                          
*○ Slater determinants (determinant group)...                                                                                                                            
*○ Configuration state functions (csf group)...                                                                                                                          
*○ Amplitudes (amplitude group)...                                                                                                                                       
*○ Reduced density matrices (rdm group)...                                                                                                                               
◉ Correlation factors                                                                                                                                                    
*○ Jastrow factor (jastrow group)...                                                                                                                    
◉ Quantum Monte Carlo data (qmc group)...                                                                                                                                

Better? :-)

**Review by q-posev — APPROVED** [review]
Thanks, Anthony! All good now, I am merging :+1:

**Pull request merged**
